### PR TITLE
Adding contributors

### LINKED ISSUE #24: Contributors Image In Readme
I think it is a great feature to add contributors image in README file. It really motivate to contributors. It is dynamically order the contributors. 

contrimga

If you want to this feature on README so I want to do this issue !! 😄

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
### What is the change?
Adding contributors in README fixes #24 

## Submissions guide:
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/AbsurdNerd/SimplifyReports/pulls) for the same update/change?
- [x] Have you made corresponding changes to the documentation?
- [x] Your submission doesn't break any existing feature.
- [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Review by plazzy99 — APPROVED** [review]
👍🏻

**Comment by Vishal-raj-1** [comment]
Please update my score to `+7`(5+2) in NWOC @plazzy99 .

**Comment by plazzy99** [comment]
> Please update my score to `+7`(5+2) in NWOC @plazzy99 .

@dheerajkotwani please do update his score for nwoc.

**Comment by dheerajkotwani** [comment]
Sure 👍

**Comment by Vishal-raj-1** [comment]
> Sure 👍

Thanks It's Done !!

**Pull request merged**
